spring.application.name=gateway-service
server.port=9000

# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración de Rutas dinámicas
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Ejemplo de Ruta personalizada para Productos
spring.cloud.gateway.routes[0].id=product-route
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
# Esto limpia el prefijo si tu controlador no tiene /api/products
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1