spring.application.name=product-service


server.port=9090


# Configuración de Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5435/product_db
spring.datasource.username=adminUser
spring.datasource.password=admin

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# --- EUREKA CLIENT ---
# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=false
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# --- CONFIGURACIÓN DE FEIGN (Opcional) ---
# Tiempo de espera para conectar con otros microservicios (en ms)
feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=5000


# --- LOGS ---
logging.level.io.github.leandro12rk.product=DEBUG