server.port=8761
spring.application.name=eureka-server

# No se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL por defecto
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/